$$
\newcommand{\diff}{\mathrm{d}}
\newcommand{\bmqty}[1]{\left[\begin{matrix} #1 \end{matrix}\right]}
$$

In [2]:
import numpy as np
pi, sin, cos, tan, arcsin, arccos, arctan, sqrt = np.pi, np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, np.sqrt
import numpy.linalg as linalg

# Creating arrays



## Data types

In [3]:
(np.array([1, 2, 3]).dtype, np.array([1., 2., 3.]).dtype, np.array([1+2j, 3j], dtype=complex).dtype)

(dtype('int32'), dtype('float64'), dtype('complex128'))

In [109]:
np.array([1., 2.3, 3.5]).astype(int)

array([1, 2, 3])

## Filling an array with initial values
`np.ones` and `np.zeroes` are used when the elements of an array are not specified but the size of the array is given.
Note that growing arrays is an expensive operation.

In [4]:

np.zeros(2)

array([0., 0.])

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones(2)

array([1., 1.])

In [7]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

It is also convenient to extract the shape and the data type of an array-like object:

In [8]:
np.ones_like([1, 2])

array([1, 1])

In [9]:
np.zeros_like([[1., 1.], [2, 1.]])

array([[0., 0.],
       [0., 0.]])

In [10]:
np.full((3, 2), 2)

array([[2, 2],
       [2, 2],
       [2, 2]])

In [11]:
np.full((2, 3), 2, dtype=float)

array([[2., 2., 2.],
       [2., 2., 2.]])

In [12]:
np.full_like([1, 2], 2)

array([2, 2])

In [13]:
np.empty((1, 2))

array([[1., 1.]])

In [14]:
np.empty_like([[2., 3.], [4., 5.]])

array([[3.83933188e-191, 8.35273634e-301],
       [3.82443268e-297, 1.19855318e-152]])

In [105]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [107]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [106]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [108]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## Number sequences

`np.arange` creates an evenly spaced number sequence with the start point, the end point and the step specified.
The end point is not included.

In [15]:
(np.arange(1), np.arange(3))

(array([0]), array([0, 1, 2]))

In [16]:
np.arange(0, 12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.arange(1, 12, 2)

array([ 1,  3,  5,  7,  9, 11])

In [18]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.linspace(0, 1, num=10, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [20]:
np.linspace(0, 1, num=10, retstep=True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

In [21]:
np.geomspace(1, 1000, num=4)

array([   1.,   10.,  100., 1000.])

In [22]:
np.geomspace(1, 1000, num=3, endpoint=False)

array([  1.,  10., 100.])

`numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)`

## Grids

In [8]:
np.mgrid[0:5:2]

array([0, 2, 4])

In [9]:
x, y = np.mgrid[0:5, 0:5]

In [10]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [11]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## From functions, iterators and so on

In [23]:
np.fromfunction(lambda x: x**2, (5,))

array([ 0.,  1.,  4.,  9., 16.])

In [24]:
np.fromfunction(lambda x, y: x*y, (3, 4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [25]:
np.fromiter(range(0, 10), dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.fromiter((x**2 for x in range(0, 5)), dtype=float, count=3)

array([0., 1., 4.])

# One-array operations

## Indexing and slicing

In [58]:
ten1 = np.array([
    [
        [1, 2],
        [3, 4],
        [4, 5]
    ],
    [
        [5, 6],
        [4, 6],
        [7, 8]
    ]
])

In [59]:
ten1[1]

array([[5, 6],
       [4, 6],
       [7, 8]])

In [60]:
ten1[1,0,0]

5

In [61]:
ten1[1,:,:]

array([[5, 6],
       [4, 6],
       [7, 8]])

In [62]:
ten1[1:,:,:]

array([[[5, 6],
        [4, 6],
        [7, 8]]])

`None` is used to create a new axis.

In [87]:
ten1[1,None]

array([[[5, 6],
        [4, 6],
        [7, 8]]])

In [86]:
ten1[1:,None]

array([[[[5, 6],
         [4, 6],
         [7, 8]]]])

In [88]:
ten1[None]

array([[[[2, 2],
         [3, 4],
         [4, 5]],

        [[5, 6],
         [4, 6],
         [7, 8]]]])

In [89]:
ten1[None, 1]

array([[[5, 6],
        [4, 6],
        [7, 8]]])

In [91]:
ten1[0, None, 0]

array([[2, 2]])

In [92]:
a = ten1[0]
a

array([[2, 2],
       [3, 4],
       [4, 5]])

In [93]:
ten1

array([[[2, 2],
        [3, 4],
        [4, 5]],

       [[5, 6],
        [4, 6],
        [7, 8]]])

In [94]:
a[0, 0] = 8
a

array([[8, 2],
       [3, 4],
       [4, 5]])

In [95]:
ten1

array([[[8, 2],
        [3, 4],
        [4, 5]],

       [[5, 6],
        [4, 6],
        [7, 8]]])

## Reshaping

In [63]:
ten1.shape

(2, 3, 2)

In [66]:
ten1.flatten()

array([1, 2, 3, 4, 4, 5, 5, 6, 4, 6, 7, 8])

In [67]:
ten1

array([[[1, 2],
        [3, 4],
        [4, 5]],

       [[5, 6],
        [4, 6],
        [7, 8]]])

In [68]:
ten1.ravel()

array([1, 2, 3, 4, 4, 5, 5, 6, 4, 6, 7, 8])

`ravel` returns a *view* of the original array; modification on the returned value effects the original array.

In [69]:
view1 = ten1.ravel()
view1[0] = 0

In [70]:
view1

array([0, 2, 3, 4, 4, 5, 5, 6, 4, 6, 7, 8])

In [80]:
ten2 = ten1.flatten()
ten2[0] = 3

In [81]:
ten1

array([[[2, 2],
        [3, 4],
        [4, 5]],

       [[5, 6],
        [4, 6],
        [7, 8]]])

In [82]:
ten2

array([3, 2, 3, 4, 4, 5, 5, 6, 4, 6, 7, 8])

In [71]:
ten1

array([[[0, 2],
        [3, 4],
        [4, 5]],

       [[5, 6],
        [4, 6],
        [7, 8]]])

In [73]:
type(ten1)

numpy.ndarray

In [78]:
view2 = ten1.reshape((2, 6))
view2

array([[2, 2, 3, 4, 4, 5],
       [5, 6, 4, 6, 7, 8]])

`reshape` also returns a view of the original data:

In [79]:
view2[0,0] = 2
view2

array([[2, 2, 3, 4, 4, 5],
       [5, 6, 4, 6, 7, 8]])

In [84]:
ten2.resize((2, 6))

In [85]:
ten2

array([[3, 2, 3, 4, 4, 5],
       [5, 6, 4, 6, 7, 8]])

## Copy

In [98]:
ten1.base

In [101]:
ten2.base

In [102]:
view1.base

array([[[8, 2],
        [3, 4],
        [4, 5]],

       [[5, 6],
        [4, 6],
        [7, 8]]])

In [103]:
view1.base is ten1

True

In [104]:
ten1.copy().base

## Enumerating

In [110]:
for index, item in np.ndenumerate(ten1):
    print(f'{str(index)} {str(item)}')

(0, 0, 0) 8
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 2, 0) 4
(0, 2, 1) 5
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 4
(1, 1, 1) 6
(1, 2, 0) 7
(1, 2, 1) 8


## Masks

In [113]:
data = ten1.flatten()

In [114]:
data > 2

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [115]:
data[data>2]

array([8, 3, 4, 4, 5, 5, 6, 4, 6, 7, 8])

In [116]:
2 < data <= 5

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [118]:
np.where(data > 2, data, -1)

array([ 8, -1,  3,  4,  4,  5,  5,  6,  4,  6,  7,  8])

`map` does not give the expected results.

In [120]:
np.where(map(lambda x: x > 2, data), data, -1)

array([8, 2, 3, 4, 4, 5, 5, 6, 4, 6, 7, 8])

In [122]:
np.where(np.fromiter(map(lambda x: x > 2, data), dtype=bool), data, -1)

array([ 8, -1,  3,  4,  4,  5,  5,  6,  4,  6,  7,  8])

## Broadcasting

# Two-Arrays operations

In [29]:
arr1 = np.array([1., 2., 3.])
arr2 = np.array([3, 4, 5])

## Logic operations

In [30]:
arr1 == arr2

array([False, False, False])

In [31]:
np.equal(arr1, arr2)

array([False, False, False])

In [32]:
np.array_equal(arr1, arr2)

False

## Linear operations

In [33]:
(arr1 + arr2, arr1 - arr2)

(array([4., 6., 8.]), array([-2., -2., -2.]))

In [34]:
(0.1 * arr2, arr2 * 2)

(array([0.3, 0.4, 0.5]), array([ 6,  8, 10]))

Note that the `*` operator means elementwise products.

In [35]:
arr1 * arr2

array([ 3.,  8., 15.])

When two objects do not have shared shapes, `*` still works.

In [36]:
mat1 = np.array([[1, 2], [0, 1]])
arr3 = np.array([1, 2])
mat1 * arr3

array([[1, 4],
       [0, 2]])

$$
\bmqty{a & b \\ c & d}  \text{  NumPy *  } \bmqty{e & f} =  \bmqty{ae & bf \\ ce & df}
$$

`@` operator is used for vector product. By default every one-dimension array is considered as a row vector, contray to the convention in mathematics.

In [37]:
arr1 @ arr2

26.0

The function of `@` is not limited to vector product.
When arrays involved can be intepreted as matrics or a matrix and a vector, 
`@` means matrix product.

In [38]:

mat2 = np.array([[2, 3], [3, 4]])
mat1 @ mat2

array([[ 8, 11],
       [ 3,  4]])

In [39]:
mat1 @ arr3

array([5, 2])

$$
\bmqty{1 & 2 \\ 0 & 1} \text{NumPy @} \bmqty{1 & 2} = \bmqty{1 & 2 \\ 0 & 1} \bmqty{1 \\ 2} = \bmqty{5 \\ 2}
$$

In [40]:
arr3 @ mat1

array([1, 4])

$$
\bmqty{1 & 2} \text{NumPy @} \bmqty{1 & 2 \\ 0 & 1} = \bmqty{1 & 2} \bmqty{1 & 2 \\ 0 & 1}  = \bmqty{1 & 4}
$$

# Linear Algebra

In [41]:
mat1

array([[1, 2],
       [0, 1]])

In [42]:
mat1.T

array([[1, 0],
       [2, 1]])

In [43]:
np.array_equal(arr1, arr1.T)

True

In [44]:
(arr1.T @ arr1, np.kron(arr1, arr1))

(14.0, array([1., 2., 3., 2., 4., 6., 3., 6., 9.]))

In [45]:
linalg.norm(arr1)

3.7416573867739413

In [46]:
linalg.det(mat1)

1.0

In [47]:
linalg.cholesky([[1, 2], [2, 5]])

array([[1., 0.],
       [2., 1.]])

$$
\bmqty{1 & 0 \\ 2 & 1} \bmqty{1 & 0 \\ 2 & 1}^\top = \bmqty{1 & 2 \\ 2 & 5}
$$

In [48]:
np.trace(mat1)

2

## Spectral decomposition

In [49]:
linalg.eig([[1, 4], [1, 1]])

(array([ 3., -1.]), array([[ 0.89442719, -0.89442719],
        [ 0.4472136 ,  0.4472136 ]]))

In [50]:
eigsys = linalg.eig([[1., 4.], [4., 1.]])
eigenvalues, eigenvectors = eigsys
(
    sum(map(lambda i: eigenvalues[i] * eigenvectors[:,i].reshape((2, 1)) @ eigenvectors[:,i].reshape((1, 2)), range(len(eigenvalues)))),
    sum(map(lambda i: eigenvalues[i] * np.outer(eigenvectors[:,i], eigenvectors[:,i]), range(len(eigenvalues))))
)

(array([[1., 4.],
        [4., 1.]]), array([[1., 4.],
        [4., 1.]]))

In [51]:
np.array([2 / sqrt(5), 1 / sqrt(5)])

array([0.89442719, 0.4472136 ])

In [52]:
(eigenvectors.T @ np.array([[1., 4.], [4., 1.]]) @ eigenvectors, eigenvalues)

(array([[ 5.,  0.],
        [ 0., -3.]]), array([ 5., -3.]))

# Universal functions

In [53]:
arr1 = np.array([1, 2, 3])

# Vectorize a function
@np.vectorize
def func1(a):
    return a*2

func1(arr1)

array([2, 4, 6])

In [4]:
def times(x, y):
    return x*y
x = np.array([1, 2, 3, 4])
y = np.array([4, 5, 6])

ValueError: not a valid gufunc signature: (n, m), (n, m) -> (n, m)